# Generated by Django 5.0.6 on 2024-06-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('subject', models.CharField(default='Empty', max_length=40)),
                ('description', models.TextField()),
            ],
        ),
    ]
